/* Generated by Spike on Sat Oct  3 00:58:32 2009 */

#include "class.h"
#include "heart.h"

static SpkOpcode module_Boolean_instance_rv___bneg___code[] = {
    Spk_OPCODE_SAVE, 0x01, 
    Spk_OPCODE_ARG, 0x00, 0x00, 0x01, 
    Spk_OPCODE_PUSH_SELF, 
    Spk_OPCODE_SEND_MESSAGE, 0x80, 0x80, 0x80, 0x00, 0x00, 
    Spk_OPCODE_POP, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_Boolean_instance_rv___bxor___code[] = {
    Spk_OPCODE_SAVE, 0x02, 
    Spk_OPCODE_ARG, 0x01, 0x00, 0x01, 
    Spk_OPCODE_PUSH_SELF, 
    Spk_OPCODE_SEND_MESSAGE, 0x80, 0x80, 0x80, 0x00, 0x00, 
    Spk_OPCODE_POP, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_Boolean_instance_rv___bor___code[] = {
    Spk_OPCODE_SAVE, 0x02, 
    Spk_OPCODE_ARG, 0x01, 0x00, 0x01, 
    Spk_OPCODE_PUSH_SELF, 
    Spk_OPCODE_SEND_MESSAGE, 0x80, 0x80, 0x80, 0x00, 0x00, 
    Spk_OPCODE_POP, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_Boolean_instance_rv___band___code[] = {
    Spk_OPCODE_SAVE, 0x02, 
    Spk_OPCODE_ARG, 0x01, 0x00, 0x01, 
    Spk_OPCODE_PUSH_SELF, 
    Spk_OPCODE_SEND_MESSAGE, 0x80, 0x80, 0x80, 0x00, 0x00, 
    Spk_OPCODE_POP, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_Boolean_instance_rv___lneg___code[] = {
    Spk_OPCODE_SAVE, 0x01, 
    Spk_OPCODE_ARG, 0x00, 0x00, 0x01, 
    Spk_OPCODE_PUSH_SELF, 
    Spk_OPCODE_SEND_MESSAGE, 0x80, 0x80, 0x80, 0x00, 0x00, 
    Spk_OPCODE_POP, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_False_instance_rv___bneg___code[] = {
    Spk_OPCODE_LEAF, 
    Spk_OPCODE_ARG, 0x00, 0x00, 0x05, 
    Spk_OPCODE_PUSH_TRUE, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_False_instance_rv___bxor___code[] = {
    Spk_OPCODE_LEAF, 
    Spk_OPCODE_ARG, 0x01, 0x00, 0x05, 
    Spk_OPCODE_PUSH_LOCAL, 0x00, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_False_instance_rv___bor___code[] = {
    Spk_OPCODE_LEAF, 
    Spk_OPCODE_ARG, 0x01, 0x00, 0x05, 
    Spk_OPCODE_PUSH_LOCAL, 0x00, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_False_instance_rv___band___code[] = {
    Spk_OPCODE_LEAF, 
    Spk_OPCODE_ARG, 0x01, 0x00, 0x05, 
    Spk_OPCODE_PUSH_FALSE, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_False_instance_rv___lneg___code[] = {
    Spk_OPCODE_LEAF, 
    Spk_OPCODE_ARG, 0x00, 0x00, 0x05, 
    Spk_OPCODE_PUSH_TRUE, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_True_instance_rv___bneg___code[] = {
    Spk_OPCODE_LEAF, 
    Spk_OPCODE_ARG, 0x00, 0x00, 0x05, 
    Spk_OPCODE_PUSH_FALSE, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_True_instance_rv___bxor___code[] = {
    Spk_OPCODE_SAVE, 0x02, 
    Spk_OPCODE_ARG, 0x01, 0x00, 0x01, 
    Spk_OPCODE_PUSH_LOCAL, 0x00, 
    Spk_OPCODE_OPER, Spk_OPER_LNEG, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_True_instance_rv___bor___code[] = {
    Spk_OPCODE_LEAF, 
    Spk_OPCODE_ARG, 0x01, 0x00, 0x05, 
    Spk_OPCODE_PUSH_TRUE, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_True_instance_rv___band___code[] = {
    Spk_OPCODE_LEAF, 
    Spk_OPCODE_ARG, 0x01, 0x00, 0x05, 
    Spk_OPCODE_PUSH_LOCAL, 0x00, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_True_instance_rv___lneg___code[] = {
    Spk_OPCODE_LEAF, 
    Spk_OPCODE_ARG, 0x00, 0x00, 0x05, 
    Spk_OPCODE_PUSH_FALSE, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_rv_Boolean_code[] = {
    Spk_OPCODE_LEAF, 
    Spk_OPCODE_ARG, 0x00, 0x00, 0x05, 
    Spk_OPCODE_PUSH_GLOBAL, 0x04, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_rv_False_code[] = {
    Spk_OPCODE_LEAF, 
    Spk_OPCODE_ARG, 0x00, 0x00, 0x05, 
    Spk_OPCODE_PUSH_GLOBAL, 0x05, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkOpcode module_rv_True_code[] = {
    Spk_OPCODE_LEAF, 
    Spk_OPCODE_ARG, 0x00, 0x00, 0x05, 
    Spk_OPCODE_PUSH_GLOBAL, 0x06, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_PUSH_VOID, 
    Spk_OPCODE_RESTORE_SENDER, 
    Spk_OPCODE_RET, 
    Spk_OPCODE_NOP
};

static SpkMethodTmpl module_Boolean_instance_rv_methods[] = {
    { "__bneg__", 0, 0, module_Boolean_instance_rv___bneg___code, sizeof(module_Boolean_instance_rv___bneg___code) },
    { "__bxor__", 0, 0, module_Boolean_instance_rv___bxor___code, sizeof(module_Boolean_instance_rv___bxor___code) },
    { "__bor__", 0, 0, module_Boolean_instance_rv___bor___code, sizeof(module_Boolean_instance_rv___bor___code) },
    { "__band__", 0, 0, module_Boolean_instance_rv___band___code, sizeof(module_Boolean_instance_rv___band___code) },
    { "__lneg__", 0, 0, module_Boolean_instance_rv___lneg___code, sizeof(module_Boolean_instance_rv___lneg___code) },
    { 0 }
};

static SpkMethodTmpl module_Boolean_instance_lv_methods[] = {
    { 0 }
};

static SpkMethodTmpl module_Boolean_class_rv_methods[] = {
    { 0 }
};

static SpkMethodTmpl module_Boolean_class_lv_methods[] = {
    { 0 }
};

SpkClassTmpl Spk_ClassBooleanTmpl = {
    Spk_HEART_CLASS_TMPL(Boolean, Object), {
        /*accessors*/ 0,
        module_Boolean_instance_rv_methods,
        module_Boolean_instance_lv_methods
    }, /*meta*/ {
        /*accessors*/ 0,
        module_Boolean_class_rv_methods,
        module_Boolean_class_lv_methods
    }
};

static SpkMethodTmpl module_False_instance_rv_methods[] = {
    { "__bneg__", 0, 0, module_False_instance_rv___bneg___code, sizeof(module_False_instance_rv___bneg___code) },
    { "__bxor__", 0, 0, module_False_instance_rv___bxor___code, sizeof(module_False_instance_rv___bxor___code) },
    { "__bor__", 0, 0, module_False_instance_rv___bor___code, sizeof(module_False_instance_rv___bor___code) },
    { "__band__", 0, 0, module_False_instance_rv___band___code, sizeof(module_False_instance_rv___band___code) },
    { "__lneg__", 0, 0, module_False_instance_rv___lneg___code, sizeof(module_False_instance_rv___lneg___code) },
    { 0 }
};

static SpkMethodTmpl module_False_instance_lv_methods[] = {
    { 0 }
};

static SpkMethodTmpl module_False_class_rv_methods[] = {
    { 0 }
};

static SpkMethodTmpl module_False_class_lv_methods[] = {
    { 0 }
};

SpkClassTmpl Spk_ClassFalseTmpl = {
    Spk_HEART_CLASS_TMPL(False, Boolean), {
        /*accessors*/ 0,
        module_False_instance_rv_methods,
        module_False_instance_lv_methods
    }, /*meta*/ {
        /*accessors*/ 0,
        module_False_class_rv_methods,
        module_False_class_lv_methods
    }
};

static SpkMethodTmpl module_True_instance_rv_methods[] = {
    { "__bneg__", 0, 0, module_True_instance_rv___bneg___code, sizeof(module_True_instance_rv___bneg___code) },
    { "__bxor__", 0, 0, module_True_instance_rv___bxor___code, sizeof(module_True_instance_rv___bxor___code) },
    { "__bor__", 0, 0, module_True_instance_rv___bor___code, sizeof(module_True_instance_rv___bor___code) },
    { "__band__", 0, 0, module_True_instance_rv___band___code, sizeof(module_True_instance_rv___band___code) },
    { "__lneg__", 0, 0, module_True_instance_rv___lneg___code, sizeof(module_True_instance_rv___lneg___code) },
    { 0 }
};

static SpkMethodTmpl module_True_instance_lv_methods[] = {
    { 0 }
};

static SpkMethodTmpl module_True_class_rv_methods[] = {
    { 0 }
};

static SpkMethodTmpl module_True_class_lv_methods[] = {
    { 0 }
};

SpkClassTmpl Spk_ClassTrueTmpl = {
    Spk_HEART_CLASS_TMPL(True, Boolean), {
        /*accessors*/ 0,
        module_True_instance_rv_methods,
        module_True_instance_lv_methods
    }, /*meta*/ {
        /*accessors*/ 0,
        module_True_class_rv_methods,
        module_True_class_lv_methods
    }
};

static SpkMethodTmpl module_rv_methods[] = {
    { "Boolean", 0, 0, module_rv_Boolean_code, sizeof(module_rv_Boolean_code) },
    { "False", 0, 0, module_rv_False_code, sizeof(module_rv_False_code) },
    { "True", 0, 0, module_rv_True_code, sizeof(module_rv_True_code) },
    { 0 }
};

static SpkMethodTmpl module_lv_methods[] = {
    { 0 }
};

