
#include "oper.h"
#include <stdio.h>


static struct {
    const char *name;
    unsigned int value;
} table[] = {
    { "numOper",     Spk_NUM_OPER      },
    { "numCallOper", Spk_NUM_CALL_OPER },
    { "operAdd",     Spk_OPER_ADD      },
    { "operAddr",    Spk_OPER_ADDR     },
    { "operApply",   Spk_OPER_APPLY    },
    { "operBAnd",    Spk_OPER_BAND     },
    { "operBNeg",    Spk_OPER_BNEG     },
    { "operBOr",     Spk_OPER_BOR      },
    { "operBXOr",    Spk_OPER_BXOR     },
    { "operDiv",     Spk_OPER_DIV      },
    { "operEq",      Spk_OPER_EQ       },
    { "operGE",      Spk_OPER_GE       },
    { "operGT",      Spk_OPER_GT       },
    { "operInd",     Spk_OPER_IND      },
    { "operIndex",   Spk_OPER_INDEX    },
    { "operLE",      Spk_OPER_LE       },
    { "operLNeg",    Spk_OPER_LNEG     },
    { "operLShift",  Spk_OPER_LSHIFT   },
    { "operLT",      Spk_OPER_LT       },
    { "operMod",     Spk_OPER_MOD      },
    { "operMul",     Spk_OPER_MUL      },
    { "operNE",      Spk_OPER_NE       },
    { "operNeg",     Spk_OPER_NEG      },
    { "operPos",     Spk_OPER_POS      },
    { "operPred",    Spk_OPER_PRED     },
    { "operRShift",  Spk_OPER_RSHIFT   },
    { "operSub",     Spk_OPER_SUB      },
    { "operSucc",    Spk_OPER_SUCC     },
    { 0 }
};


int main() {
    int i;
    
    printf("    // automatically generated by oper.c\n");
    
    for (i = 0; table[i].name; ++i) {
        printf("    %s { return %d; }\n",
               table[i].name, table[i].value);
    }
    
    return 0;
}
