
#include "oper.h"
#include <stdio.h>


static struct {
    const char *name;
    unsigned int value;
} table[] = {
    { "numOper",     NUM_OPER      },
    { "numCallOper", NUM_CALL_OPER },
    { "operAdd",     OPER_ADD      },
    { "operAddr",    OPER_ADDR     },
    { "operApply",   OPER_APPLY    },
    { "operBAnd",    OPER_BAND     },
    { "operBNeg",    OPER_BNEG     },
    { "operBOr",     OPER_BOR      },
    { "operBXOr",    OPER_BXOR     },
    { "operDiv",     OPER_DIV      },
    { "operEq",      OPER_EQ       },
    { "operGE",      OPER_GE       },
    { "operGT",      OPER_GT       },
    { "operInd",     OPER_IND      },
    { "operIndex",   OPER_INDEX    },
    { "operLE",      OPER_LE       },
    { "operLNeg",    OPER_LNEG     },
    { "operLShift",  OPER_LSHIFT   },
    { "operLT",      OPER_LT       },
    { "operMod",     OPER_MOD      },
    { "operMul",     OPER_MUL      },
    { "operNE",      OPER_NE       },
    { "operNeg",     OPER_NEG      },
    { "operPos",     OPER_POS      },
    { "operPred",    OPER_PRED     },
    { "operRShift",  OPER_RSHIFT   },
    { "operSub",     OPER_SUB      },
    { "operSucc",    OPER_SUCC     },
    { 0 }
};


int main() {
    int i;
    
    printf("    // automatically generated by oper.c\n");
    
    for (i = 0; table[i].name; ++i) {
        printf("    %s { return %d; }\n",
               table[i].name, table[i].value);
    }
    
    return 0;
}
