#!/usr/bin/env python


def dump(filename):
    from spike.compiler import Notifier, parse #, trace
    from sys import stdout

    notifier = Notifier()

    #trace(stdout, "")
    tree = parse(filename, notifier)

    notifier.failOnError()

    tree.dump(stdout)
    
    dot = "ast.dot"
    #dot = "/dev/null"
    stream = open(dot, "w")
    print >>stream, "digraph AST {"
    tree.graphviz(stream)
    print >>stream, "}"
    stream.close()



import sys
for filename in sys.argv[1:]:
    print filename
    dump(filename)
