#!/bin/sh

top_srcdir=$1
spike=$2
test_source=$3

PYTHONPATH=$top_srcdir

d=`dirname $test_source`
b=`basename $test_source .spk`
control=$d/$b.out
control_err=$d/$b.err
input=$d/$b.in

$spike $test_source $input > test.out 2> test.tmp
status=$?
grep tests test.tmp | cut -d : -f 2- > test.err

if test -f $control_err ; then
    if test $status -eq 1 ; then
        diff $control test.out
        status=$?
        if test $status -eq 0 ; then
            diff $control_err test.err
            status=$?
        fi
    fi
elif test $status -eq 0 ; then
    diff $control test.out
    status=$?
fi

exit $status
